export const items =  [
    {
      id: 1,
      category: 'mexican',
      title: "Restaurants 1",
      imgSrc: 'https://img.freepik.com/free-photo/ancient-chinise-room_1417-1692.jpg?t=st=1710844847~exp=1710848447~hmac=cf67e462ed729b847d6e580f0f59efddf00a41ee6b0f2c40c15ed1611de72f76&w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-regular fa-star",
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'MEXICAN . $$$',
      circleopen: 'fa-solid fa-circle fa-sm',
      opennow: 'OPEN NOW',
      price: '10.00',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 2,
      category: 'thailand',
      title: "Restaurants 2",
      imgSrc: 'https://img.freepik.com/premium-photo/beautiful-loft-style-interior-with-fireplace-dining-table-decorated-new-year-holidays_506452-4444.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-regular fa-star",
      star5: "fa-regular fa-star",
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'THAILAND . $$ ',
      circleclose: 'fa-solid fa-circle fa-sm',
      opennow: 'CLOSED',
      price: '13.10',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 3,
      category: 'japanesse',
      title: "Restaurants 3",
      imgSrc: 'https://img.freepik.com/free-photo/interior-shot-cafe-with-chairs-near-bar-with-wooden-tables_181624-1669.jpg?w=740&t=st=1711547343~exp=1711547943~hmac=5e41d3827cc81ae7115287f69af012d74d7a47da8c67bed4bee8fe154339795f',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star-half-stroke",
      star5: "fa-regular fa-star",
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'JAPANESSE . $',
      circleopen: 'fa-solid fa-circle fa-sm',
      opennow: 'OPEN NOW',
      price: '7.15',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 4,
      category: 'american',
      title: "Restaurant 4",
      imgSrc: 'https://img.freepik.com/free-photo/restaurant-interior_1127-3394.jpg?t=st=1711547451~exp=1711551051~hmac=09776105d18dddcbb4bbb737e4e45d26edd72ad58be4f0f21b493eb894e7021a&w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star-half-stroke",
      star5: "fa-regular fa-star",
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'AMERICAN . $$$$',
      circleopen: 'fa-solid fa-circle fa-sm',
      opennow: 'OPEN NOW',
      price: '15.20',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },
    {
      id: 5,
      category: 'japanesse',
      title: "Restaurant 5",
      imgSrc: 'https://img.freepik.com/free-photo/restaurant-hall-with-lots-table_140725-6309.jpg?w=740&t=st=1711919860~exp=1711920460~hmac=04109a4017e44b8b29a1ff25a7523454855935c9d2024d8786df4a3903f303ef',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-regular fa-star",
      star5: "fa-regular fa-star",
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'JAPANESSE . $$$$',
      circleclose: 'fa-solid fa-circle fa-sm',
      opennow: 'CLOSED',
      price: '15.20',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 6,
      category: 'mexican',
      title: "Restaurant 6",
      imgSrc: 'https://img.freepik.com/premium-photo/interior-lounge-architecture-entertainment-relaxation_482257-9581.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'MEXICAN . $',
      circleopen: 'fa-solid fa-circle fa-sm',
      opennow: 'OPEN NOW',
      price: '7.15',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },
    
    {
      id: 7,
      category: 'american',
      title: "Restaurant 7",
      imgSrc: 'https://img.freepik.com/premium-photo/interior-restaurant-modern-design-few-colors-orange-blue_79762-2596.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'AMERICAN . $$$',
      opennow: 'OPEN NOW',
      circleopen: 'fa-solid fa-circle fa-sm',
      price: '10.00',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 8,
      category: 'thailand',
      title: "Restaurant 8",
      imgSrc: 'https://img.freepik.com/premium-photo/guests-woman-bartender-old-fashioned-restaurant_175935-799.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'THAILAND . $$',
      opennow: 'OPEN NOW',
      circleopen: 'fa-solid fa-circle fa-sm',
      price: '13.10',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 9,
      category: 'american',
      title: "Restaurant 9",
      imgSrc: 'https://img.freepik.com/free-photo/restaurant-interior_1127-3393.jpg?t=st=1711547731~exp=1711551331~hmac=6f06c9adb848c0ae5a156ab0faa8e4772c536aef54836590ea0349e8b6e8fc79&w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'AMERICAN . $$$$',
      circleopen: 'fa-solid fa-circle fa-sm',
      opennow: 'OPEN NOW',
      price: '15.20',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 10,
      category: 'japanesse',
      title: "Restaurant 10",
      imgSrc: 'https://img.freepik.com/premium-photo/cafe-coffee-decorated-warm-colors-makes-it-look-warm-suitable-resting-sitting-shop-furniture-uses-brown-iron-chairs-tabletop-uses-white-marble-soft-seat-tone-control_128338-27.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'JAPANESSE . $$$',
      circleopen: 'fa-solid fa-circle fa-sm',
      opennow: 'OPEN NOW',
      price: '10.00',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 11,
      category: 'thailand',
      title: "Restaurant 11",
      imgSrc: 'https://img.freepik.com/premium-photo/empty-tables-street-cafe-morning-istanbul_93675-124348.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'THAILAND . $$',
      circleclose: 'fa-solid fa-circle fa-sm',
      opennow: 'CLOSED',
      price: '13.10',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 12,
      category: 'mexican',
      title: "Restaurant 12",
      imgSrc: 'https://img.freepik.com/free-photo/table-set-dinning-table_1339-3434.jpg?t=st=1711547829~exp=1711551429~hmac=746013c8ce98bc3f352a802b1feb0cadc7c22674217f27e681cfd5681b7b8de0&w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'MEXICAN . $',
      circleopen: 'fa-solid fa-circle fa-sm',
      opennow: 'OPEN NOW',
      price: '7.15',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 13,
      category: 'mexican',
      title: "Restaurant 13",
      imgSrc: 'https://img.freepik.com/premium-photo/loft-luxury-hotel-reception-cafe-lounge-restaurant_105762-1774.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'MEXICAN . $',
      opennow: 'OPEN NOW',
      circleopen: 'fa-solid fa-circle fa-sm',
      price: '7.15',

      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 14,
      category: 'japanesse',
      title: "Restaurant 14",
      imgSrc: 'https://img.freepik.com/premium-photo/modern-shabu-sukiyaki-restaurant-decorated-with-wood-concrete_43263-1838.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'JAPANESSE . $$$$',
      opennow: 'OPEN NOW',
      circleopen: 'fa-solid fa-circle fa-sm',
      price: '15.20',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 15,
      category: 'thailand',
      title: "Restaurant 15",
      imgSrc: 'https://img.freepik.com/premium-photo/shabu-dining-table-set-including-one-wooden-table-seats-ground-with-bamboo-ceiling_43263-1101.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'THAILAND . $$',
      opennow: 'OPEN NOW',
      price: '13.10',
      circleopen: 'fa-solid fa-circle fa-sm',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

    {
      id: 16,
      category: 'american',
      title: "Restaurant 16",
      imgSrc: 'https://img.freepik.com/premium-photo/iron-chair-with-leather-seat-back-seats-place-front-wooden-wall_43263-970.jpg?w=740',
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'AMERICAN . $$$',
      circleclose: 'fa-solid fa-circle fa-sm',
      opennow: 'CLOSED',
      price: '10.00',
      bttn:'fa-solid fa-angle-left fa-2xl',
      isi: 'Hershey oldest restaurant still standing. A local favorite for over 83 years. Serving DeAngelis spaghetti sauce and our famous Upside Down pizza. Seafood, steaks and pasta with a taste of delicious Italian home cooking.',
    },

  ]